services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile.dev
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - assets_data:/assets
    ports:
      - "3333:3333"
    env_file: ".env.local"
    command: npm run dev:server

  postgres:
    image: postgres:15
    env_file: ".env.local"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  client-web:
    build:
      context: .
      dockerfile: apps/client-web/Dockerfile.dev
    volumes:
      - .:/workspace
      - /workspace/node_modules
    ports:
      - "3000:3000"
    env_file: ".env.local"
    depends_on:
      - server
    command: npm run dev:client-web

volumes:
  postgres_data:
  assets_data:
